name: Build development container

on:
  push:
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            file: Dockerfile
            image: ghcr.io/marijnvanwezel/haskell-dev-env

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2b51285047da1547ffb1b2203d8be4c0af6b1f20

      - name: Build and push image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          # https://github.com/moby/buildkit#github-actions-cache-experimental
          cache-from: type=gha
          cache-to: type=gha,mode=max
